services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: proyectoweb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: proyectoweb_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/proyectoweb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    ports:
      - "8080:8080"

volumes:
  pgdata:
